//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        { }
        public Activity(string name, string description, DateTime activity_Date)
        {
            Name = name;
            Description = description;
            Activity_Date = activity_Date;
            Date_Created = DateTime.Now;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Activity_Date { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
