//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diaper
    {
        public Diaper()
        { }
        public Diaper(int numberOfDiapers, DateTime date_Used)
        {
            NumberOfDiapers = numberOfDiapers;
            Date_Used = date_Used;
            Date_Created = DateTime.Now;
        }

        public int Id { get; set; }
        public int NumberOfDiapers { get; set; }
        public System.DateTime Date_Used { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
