//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        { }
        public Food(string name, string type, string description, DateTime date_Taken)
        {
            Name = name;
            Type = type;
            Description = description;
            Date_Taken = date_Taken;
            Date_Created = DateTime.Now;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Taken { get; set; }
    }
}
