//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KidsDairyEntities : DbContext
    {
        public KidsDairyEntities()
            : base("name=KidsDairyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Diaper> Diapers { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Outing> Outings { get; set; }
        public virtual DbSet<Sleep> Sleeps { get; set; }
    }
}
