//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outing
    {
        public Outing()
        { }
        public Outing(string name, DateTime outing_Date, string desciption)
        {
            Name = name;
            Outing_Date = outing_Date;
            Desciption = desciption;
            Date_Created = DateTime.Now;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Outing_Date { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Desciption { get; set; }
    }
}
