//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sleep
    {
        public Sleep()
        { }
        public Sleep(DateTime sleep_Time, DateTime wakeUp_Time)
        {
            Sleep_Time = sleep_Time;
            WakeUp_Time = wakeUp_Time;
            Date_Created = DateTime.Now;
        }

        public int Id { get; set; }
        public System.DateTime Sleep_Time { get; set; }
        public System.DateTime WakeUp_Time { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
